# Generated by Django 4.1.2 on 2023-07-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_libelle', models.TextField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='editeur_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='editeur_id',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.RemoveField(
            model_name='voteartcile',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='voteartcile',
            name='editeur_id',
        ),
        migrations.DeleteModel(
            name='article',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='observation',
        ),
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.DeleteModel(
            name='voteArtcile',
        ),
    ]
