# Generated by Django 4.1.2 on 2023-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlab', '0003_article_comment_observation_profil_usermanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
