# Generated by Django 4.1.2 on 2023-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlab', '0004_alter_category_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profil_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voteartcile',
            name='vote_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
