# Generated by Django 4.1.2 on 2023-08-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlab', '0009_rename_observation_observation_observation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
