# Generated by Django 4.1.2 on 2023-08-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlab', '0010_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanager',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='first_connexion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backlab.profil', verbose_name='user_profil'),
        ),
    ]
