# Generated by Django 4.1.2 on 2023-08-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlab', '0012_alter_usermanager_options_alter_usermanager_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
