# Generated by Django 4.1.2 on 2023-08-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlab', '0013_alter_usermanager_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
