# Generated by Django 4.1.2 on 2023-08-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlab', '0014_alter_usermanager_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='profil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backlab.profil', verbose_name='user_profil'),
        ),
    ]
